services:
  redis:
    image: redis:7.0.15
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    environment:
      TOKEN: ${TOKEN}
      EMAIL: ${EMAIL}
      API: ${API}
      DATABASE_URL: ${DATABASE_URL}

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    restart: always